---
- hosts: vu10-2-0*
  become: yes
  tasks:
    - name: Установка Java
      apt:
        name: openjdk-11-jre
        state: present
        update_cache: yes

    - name: Загрузка и установка Nextflow
      shell: |
        wget -qO- https://get.nextflow.io | bash
        mv nextflow /usr/local/bin/
      args:
        creates: /usr/local/bin/nextflow

    - name: Change nextflow executable mode
      file:
        path: /usr/local/bin/nextflow
        mode: '0755'