---
- hosts: all
  become: yes
  tasks:
    - name: Установка MUNGE
      apt:
        name: munge
        state: present
        update_cache: yes
      tags:
        - install

    - name: Генерация ключа MUNGE на контроллере
      command: /usr/sbin/create-munge-key
      when: inventory_hostname == "dgx10"
      tags:
        - key

    - name: Копирование ключа MUNGE на узлы
      copy:
        src: /etc/munge/munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'
        remote_src: yes
      when: inventory_hostname != "dgx10"
      delegate_to: dgx10
      tags:
        - copy_key

    - name: Запуск и включение MUNGE на всех узлах
      systemd:
        name: munge
        enabled: yes
        state: started
      tags:
        - start