---
- hosts: all
  become: yes
  vars:
    slurm_version: "24.05.4"  # Версия SLURM для установки
    slurm_tarball: "slurm-{{ slurm_version }}.tar.bz2"
    slurm_url: "https://download.schedmd.com/slurm/{{ slurm_tarball }}"

  tasks:
    # Установка зависимостей для сборки пакетов
    - name: Установить зависимости для сборки пакетов
      apt:
        name:
          - build-essential
          - fakeroot
          - devscripts
          - equivs
        state: present
        update_cache: yes
      tags: make_deps

    # Скачивание SLURM исходников
    - name: Скачать исходники SLURM
      get_url:
        url: "{{ slurm_url }}"
        dest: "/tmp/{{ slurm_tarball }}"
      tags: make_deps

    # Распаковка исходников
    - name: Распаковать SLURM исходники
      ansible.builtin.unarchive:
        src: "/tmp/{{ slurm_tarball }}"
        dest: /tmp/
        remote_src: yes
      args:
        creates: "/tmp/slurm-{{ slurm_version }}"
      tags: make_deps
      
    # Установка зависимостей SLURM пакетов
    - name: Установить зависимости SLURM из control-файла
      expect:
        command: >
          mk-build-deps -i debian/control
        responses:
            'Do you want to continue? [Y/n]' : 'y'
      args:
        chdir: "/tmp/slurm-{{ slurm_version }}"
          
      tags: make_deps
      
    # Сборка пакетов SLURM
    - name: Собрать пакеты SLURM
      command: >
        debuild -b -uc -us
      args:
        chdir: "/tmp/slurm-{{ slurm_version }}"
      tags: build_slurm
      
    # Установка пакетов SLURM в зависимости от типа узла
    - name: Добавить SLURM пакеты на контроллер
      apt:
        deb: "/tmp/slurm-{{ slurm_version }}/slurm-smd*{{ slurm_version }}*.deb"
      when: inventory_hostname in groups['slurm_controller']
      tags: build_slurm
      
    - name: Добавить SLURM пакеты на узлы
      apt:
        deb: "/tmp/slurm-{{ slurm_version }}/slurm-smd*{{ slurm_version }}*.deb"
      when: inventory_hostname in groups['slurm_cpu_nodes']
      tags: build_slurm

      # Установка пакетов SLURM в зависимости от типа узла
    - name: Установить SLURM пакеты на контроллер
      apt:
        deb={{ item }}
      with_items:
        - /tmp/slurm-smd_24.05.4-1_amd64.deb
        - /tmp/slurm-smd-slurmctld_24.05.4-1_amd64.deb
        - /tmp/slurm-smd-client_24.05.4-1_amd64.deb
      when: inventory_hostname in groups['slurm_controller']
      tags: install_slurm
      
    - name: Установить SLURM пакеты на узлы
      apt:
        deb={{ item }}
      with_items:
        - /tmp/slurm-smd_24.05.4-1_amd64.deb
        - /tmp/slurm-smd-slurmd_24.05.4-1_amd64.deb
        - /tmp/slurm-smd-client_24.05.4-1_amd64.deb
      when: inventory_hostname in groups['slurm_cpu_nodes']
      tags: install_slurm


    # Создание необходимых директорий для SLURM
    - name: Создание необходимых директорий для SLURM
      file:
        path: "{{ item }}"
        state: directory
        owner: slurm
        group: slurm
      with_items:
        - /etc/slurm
        - /var/spool/slurm-llnl
        - /var/spool/slurmd
        - /var/log/slurm
      tags:
        - config

    # Копирование конфигурации slurm.conf на все узлы
    - name: Копирование конфигурации slurm.conf
      template:
        src: slurm.conf.j2
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: '0644'
      tags:
        - config

    # Запуск и включение SLURM демонов на всех узлах
    - name: Запуск SLURM на всех узлах
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - slurmd
      tags:
        - start

- hosts: slurm_controller
  become: yes
  tasks:
    # Запуск контроллера SLURM на контроллере
    - name: Запуск SLURM контроллера
      systemd:
        name: slurmctld
        enabled: yes
        state: started
      tags:
        - start