---
- hosts: all
  become: yes
  tasks:
    # Установка SLURM
    - name: Установка SLURM
      apt:
        name: slurm-wlm
        state: present
        update_cache: yes
      tags:
        - install

    # Создание необходимых директорий для SLURM
    - name: Создание необходимых директорий для SLURM
      file:
        path: "{{ item }}"
        state: directory
        owner: slurm
        group: slurm
      with_items:
        - /etc/slurm
        - /var/spool/slurm-llnl
        - /var/spool/slurmd
        - /var/log/slurm
      tags:
        - config

    # Копирование конфигурации slurm.conf на все узлы
    - name: Копирование конфигурации slurm.conf
      template:
        src: slurm.conf.j2
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: '0644'
      tags:
        - config

    # Запуск и включение SLURM демонов на всех узлах
    - name: Запуск SLURM на всех узлах
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      with_items:
        - slurmd
      tags:
        - start

- hosts: slurm_controller
  become: yes
  tasks:
    # Запуск контроллера SLURM на контроллере
    - name: Запуск SLURM контроллера
      systemd:
        name: slurmctld
        enabled: yes
        state: started
      tags:
        - start