---
- hosts: all
  become: yes
  tasks:
    # Резервное копирование конфигурационных файлов SLURM
    - name: Создание резервной копии slurm.conf
      copy:
        src: /etc/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf.backup
        remote_src: yes
      ignore_errors: yes

    - name: Создание резервной копии slurmdbd.conf (если используется slurmdbd)
      copy:
        src: /etc/slurm/slurmdbd.conf
        dest: /etc/slurm/slurmdbd.conf.backup
        remote_src: yes
      ignore_errors: yes

    # Добавление репозитория SLURM
    - name: Добавить репозиторий SLURM
      apt_repository:
        repo: "ppa:ubuntuhpc/slurm"
        state: present
        update_cache: yes

    # Удаление текущей версии SLURM (если нужно)
    - name: Удалить текущую версию SLURM
      apt:
        name: slurm-wlm
        state: absent
      ignore_errors: yes

    # Установка последней версии SLURM
    - name: Установить последнюю версию SLURM
      apt:
        name: slurm-wlm
        state: latest

    # Перезапуск slurmd и slurmctld
    - name: Перезапуск slurmd и slurmctld
      systemd:
        name: "{{ item }}"
        state: restarted
      with_items:
        - slurmd
        - slurmctld
      when: inventory_hostname in groups['slurm_controller']  # Только на контроллере перезапускаем slurmctld
